apiVersion: apps/v1
kind: Deployment
metadata:
  name: foundry-dnd-beyond-rolls-companion
  labels:
    app: foundry-dnd-beyond-rolls-companion
spec:
  replicas: 1
  selector:
    matchLabels:
      app: foundry-dnd-beyond-rolls-companion
  template:
    metadata:
      labels:
        app: foundry-dnd-beyond-rolls-companion
    spec:
      containers:
        - name: foundry-dnd-beyond-rolls-companion
          image: mbround18/fvtt-dndbeyond-companion:latest
          ports:
            - containerPort: 8745
              name: http
          livenessProbe:
            httpGet:
              path: /liveliness
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /readiness
              port: http
            initialDelaySeconds: 10
            periodSeconds: 5
          startupProbe:
            httpGet:
              path: /startup
              port: http
            initialDelaySeconds: 10
            periodSeconds: 5
