apiVersion: v1
kind: Service
metadata:
  name: foundry-dnd-beyond-rolls-companion
spec:
  selector:
    app: foundry-dnd-beyond-rolls-companion
  ports:
    - protocol: TCP
      port: 80
      name: http
      targetPort: http
